update=3/10/2007-23:32:04
last_client=kicad
[cvpcb]
version=1
NetITyp=0
NetIExt=.net
PkgIExt=.pkg
NetType=0
[cvpcb/libraries]
EquName1=ci
EquName2=devcms
EquName3=device
[common]
NetDir=
[pcbnew]
[pcbnew/libraries]
LibDir=
LibName1=supports
LibName2=muonde
LibName3=connect
LibName4=discret
LibName5=pin_array
LibName6=divers
LibName7=libcms
LibName8=display
[general]
version=1
RootSch=motorswitch.sch
BoardNm=motorswitch.brd
